author: "Tobe O <thosakwe@gmail.com>"
description: "Error handling plugin for Angel."
homepage: "https://github.com/angel-dart/errors.git"
name: "angel_errors"
version: "1.0.0-dev+1"
dependencies: 
  angel_framework: "^1.0.0-dev"
dev_dependencies: 
  angel_test: "^1.0.0-dev"
  test: "^0.12.17+2"
environment: 
  sdk: ">=1.19.0"
